services:
  - type: web
    name: maria-havens
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python init_db.py
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: maria-havens-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: main.py
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: true
      - key: MAIL_USERNAME
        value: jabezmageto78@gmail.com
      - key: MAIL_PASSWORD
        value: kwjn rrno dnbm usxl
      - key: MAIL_DEFAULT_SENDER
        value: jabezmageto78@gmail.com

databases:
  - name: maria-havens-db
    plan: free